### ISSUE TITLE
listUsers face only shows admin, regardless of users that exist

### ISSUE THREAD

**Issue by wolfspyre** [ekristen/docker-index-cli#4]
I've gotten a running docker-index in my lab provisioned from the following fig.yml 
## fig/registry/fig.yml 

```
registrycache:
  image: dockerfile/redis:latest
  command: redis-server /etc/redis/redis.conf --maxmemory-policy allkeys-lru
indexcache:
  image: dockerfile/redis:latest
  command: redis-server /etc/redis/redis.conf
registry:
  build: ../../images/registry
  links:
    - registrycache
  environment:
    - SEARCH_BACKEND=sqlalchemy
    - CACHE_LRU_REDIS_HOST=registrycache
    - CACHE_LRU_REDIS_PORT=6379
    - STORAGE_PATH=/docker-registry
    - LOGLEVEL=debug
    - INDEX_ENDPOINT=https://index.wolfspyre.io
index:
  build: ../../images/docker-index
  ports:
    - "5100:5100"
  environment:
    - REGISTRIES=dkr-reg.wolfspyre.io
  links:
    - "indexcache:redis"
proxy:
  build: ../../images/nginx-wolfspyre
  ports:
    - "443:443"
  links:
    - registry
    - index
  volumes:
    - config/wolfspyre/nginx/sites-enabled:/etc/nginx/sites-enabled
    - logs/nginx:/var/log/nginx
```

This appears to work acceptably, I can create users:

```
root@euc-int-aus-dog-dkr-reg-001:~# docker login -u deploy -e deploy@wolfspyre.io -p REDACTED index.wolfspyre.io
Account created. Please see the documentation of the registry https://index.wolfspyre.io/v1/ for instructions how to activate it.
root@euc-int-aus-dog-dkr-reg-001:~# docker login -u wolfspyre -e wolfspyre@wolfspyre.io -p REDACTED index.wolfspyre.io
Account created. Please see the documentation of the registry https://index.wolfspyre.io/v1/ for instructions how to activate it.
root@euc-int-aus-dog-dkr-reg-001:~# docker login -u admin -e wolf@wolfspyre.io -p REDACTED  index.wolfspyre.io
Account created. Please see the documentation of the registry https://index.wolfspyre.io/v1/ for instructions how to activate it.
```

I can also interact with the index via the CLI; which I install thusly:

```
apt-get install virtualenvwrapper; source /etc/bash_completion
mkvirtualenv docker-index; pip install nodeenv ; nodeenv -p
npm install -g ekristen/docker-index-cli
workon docker-index
```

From there, I can use the cli:

```
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index enableUser deploy@index.wolfspyre.io
{"message":"account enabled","user":"deploy"}
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index enableUser wolfspyre@index.wolfspyre.io
{"message":"account enabled","user":"wolfspyre"}


(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index getUser deploy@index.wolfspyre.io
User Details

  Username: deploy
     Email: deploy@wolfspyre.io
  Disabled: false

Permissions:


(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index getUser wolfspyre@index.wolfspyre.io
User Details

  Username: wolfspyre
     Email: wolfspyre@wolfspyre.io
  Disabled: false

Permissions:
```

It definitely behaves differently when asking for details of a nonexistent user:

```
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index getUser invalid_user@index.wolfspyre.io
Error: {"message":"invalid user","error":false}
```

However when asking for a list of users, it only ever lists admin:

```
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index listUsers index.wolfspyre.io
Username
--------
admin   
```

I tried giving a different user the same privileges that the admin user has:

```
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index listPermissions admin@index.wolfspyre.io
Permissions for admin on index.wolfspyre.io

Namespace/Repo  Access Level
--------------  ------------
test            admin       
admin           admin       
dockerfile      admin

(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index listPermissions wolfspyre@index.wolfspyre.io
Permissions for wolfspyre on index.wolfspyre.io

Namespace/Repo  Access Level
--------------  ------------
admin           admin       
dockerfile      admin       
test            admin       
```

However that did not impact anything

```
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker login -u wolfspyre -p REDACTED -e wolfspyre@wolfspyre.io index.wolfspyre.io
Account created. Please see the documentation of the registry https://index.wolfspyre.io/v1/ for instructions how to activate it.
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index listUsers index.wolfspyre.io
Error: {"message":"access denied"}

(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker login -u admin -e indexadmin@wolfspyre.io -p REDACTED  index.wolfspyre.io
Account created. Please see the documentation of the registry https://index.wolfspyre.io/v1/ for instructions how to activate it.
(docker-index)root@euc-int-aus-dog-dkr-reg-001:~# docker-index listUsers index.wolfspyre.io
Username
--------
admin   
```

I'm not sure if this is a cli bug, or an index bug.

Is there anything else you'd need to help diagnose this?
